const medications = [
  // ANTIBIOTIC AND ANTIMICROBIAL
  { code:"ANT001", brand:"Benzapen 1.2 million injection", generic:"Benzathine Penicillin", strength:"1.2 million/Vial", price:180 },
  { code:"ANT002", brand:"Cef-3 Capsule", generic:"Cefixime", strength:"200 mg", price:55 },
  { code:"ANT003", brand:"Cef-3 DS Capsule", generic:"Cefixime", strength:"400 mg", price:100 },
  { code:"ANT004", brand:"Cef-3 Dry Syrup", generic:"Cefixime", strength:"100 mg/5ml", price:110 },
  { code:"ANT005", brand:"Cefotil 125 Tablet", generic:"Cefuroxime Axetil", strength:"125 mg", price:25 },
  { code:"ANT006", brand:"Cefotil 250 Tablet", generic:"Cefuroxime Axetil", strength:"250 mg", price:45 },
  { code:"ANT007", brand:"Cefotil 500 Tablet", generic:"Cefuroxime Axetil", strength:"500 mg", price:80 },
  { code:"ANT008", brand:"Cefotil Suspension", generic:"Cefuroxime Axetil", strength:"125 mg/5ml", price:130 },
  { code:"ANT009", brand:"Cefotil IM/IV Injection", generic:"Cefuroxime Sodium", strength:"750 mg", price:200 },
  { code:"ANT010", brand:"Cefotil 1.5 Injection", generic:"Cefuroxime Sodium", strength:"1.5 gm", price:350 },
  { code:"ANT011", brand:"Ceftron 1gm IM/IV Inj.", generic:"Ceftriaxone", strength:"1 gm", price:220 },
  { code:"ANT012", brand:"Ceftron 2gm IV Inj.", generic:"Ceftriaxone", strength:"2 gm", price:400 },
  { code:"ANT013", brand:"Ceftron 250 IM/IV Inj.", generic:"Ceftriaxone", strength:"250 mg", price:75 },
  { code:"ANT014", brand:"Ceftron 500 IM/IV Inj.", generic:"Ceftriaxone", strength:"500 mg", price:130 },
  { code:"ANT015", brand:"Ciprocin 250 Tablet", generic:"Ciprofloxacin", strength:"250 mg", price:8 },
  { code:"ANT016", brand:"Ciprocin 500 Tablet", generic:"Ciprofloxacin", strength:"500 mg", price:14 },
  { code:"ANT017", brand:"Ciprocin 750 Tablet", generic:"Ciprofloxacin", strength:"750 mg", price:20 },
  { code:"ANT018", brand:"Ciprocin Suspension", generic:"Ciprofloxacin", strength:"250 mg/5ml", price:120 },
  { code:"ANT019", brand:"Ciprocin XR 1000 Tablet", generic:"Ciprofloxacin", strength:"1000 mg", price:30 },
  { code:"ANT020", brand:"Cotrim Suspension", generic:"Sulphamethoxazole+Trimethoprim", strength:"(200+40) mg/5ml", price:60 },
  { code:"ANT021", brand:"Cotrim Tablet", generic:"Sulphamethoxazole+Trimethoprim", strength:"400+80 mg", price:3 },
  { code:"ANT022", brand:"Cotrim DS Tablet", generic:"Sulphamethoxazole+Trimethoprim", strength:"800+160 mg", price:5 },
  { code:"ANT023", brand:"Doxacil 100 Capsule", generic:"Doxycycline HCl", strength:"100 mg", price:5 },
  { code:"ANT024", brand:"Emcil Tablet", generic:"Pivmecillinam", strength:"200 mg", price:18 },
  { code:"ANT025", brand:"Eromycin 250 Tablet", generic:"Erythromycin", strength:"250 mg", price:8 },
  { code:"ANT026", brand:"Eromycin Dry Syrup", generic:"Erythromycin", strength:"125 mg/5ml", price:85 },
  { code:"ANT027", brand:"Eromycin DS Tablet", generic:"Erythromycin", strength:"500 mg", price:14 },
  { code:"ANT028", brand:"Eromycin Pediatric Drops", generic:"Erythromycin Ethylsuccinate", strength:"200 mg/5ml", price:95 },
  { code:"ANT029", brand:"Force 1gm IV Injection", generic:"Cefpirome", strength:"1 gm", price:450 },
  { code:"ANT030", brand:"Gati 400 Tablet", generic:"Gatifloxacin", strength:"400 mg", price:30 },
  { code:"ANT031", brand:"Genacyn 20 Injection", generic:"Gentamicin", strength:"20 mg/2ml", price:15 },
  { code:"ANT032", brand:"Genacyn 80 Injection", generic:"Gentamicin", strength:"80 mg/2ml", price:25 },
  { code:"ANT033", brand:"Lebac 1gm IV Injection", generic:"Cephradine", strength:"1 gm", price:160 },
  { code:"ANT034", brand:"Lebac 500mg Injection", generic:"Cephradine", strength:"500 mg", price:95 },
  { code:"ANT035", brand:"Lebac 250 Capsule", generic:"Cephradine", strength:"250 mg", price:10 },
  { code:"ANT036", brand:"Lebac 500 Capsule", generic:"Cephradine", strength:"500 mg", price:18 },
  { code:"ANT037", brand:"Lebac Dry Syrup", generic:"Cephradine", strength:"125 mg/5ml", price:90 },
  { code:"ANT038", brand:"Lebac Pediatric Drops", generic:"Cephradine", strength:"125 mg/1.25ml", price:75 },
  { code:"ANT039", brand:"Lebac Forte Suspension", generic:"Cephradine", strength:"250 mg/5ml", price:130 },
  { code:"ANT040", brand:"Maxcef 250mg Injection", generic:"Cefotaxime", strength:"250 mg", price:65 },
  { code:"ANT041", brand:"Maxcef 500mg Injection", generic:"Cefotaxime", strength:"500 mg", price:110 },
  { code:"ANT042", brand:"Maxcef 1gm Injection", generic:"Cefotaxime", strength:"1 gm", price:190 },
  { code:"ANT043", brand:"Mexlo 400 Tablet", generic:"Lomefloxacin", strength:"400 mg", price:25 },
  { code:"ANT044", brand:"Moxacil 250 Capsule", generic:"Amoxycillin Trihydrate", strength:"250 mg", price:5 },
  { code:"ANT045", brand:"Moxacil 500 Injection", generic:"Amoxycillin", strength:"500 mg/vial", price:40 },
  { code:"ANT046", brand:"Moxacil 500 Capsule", generic:"Amoxycillin Trihydrate", strength:"500 mg", price:9 },
  { code:"ANT047", brand:"Moxacil Dry Syrup", generic:"Amoxycillin", strength:"125 mg/5ml", price:70 },
  { code:"ANT048", brand:"Moxacil Forte Suspension", generic:"Amoxycillin", strength:"250 mg/5ml", price:110 },
  { code:"ANT049", brand:"Moxacil DT", generic:"Amoxycillin", strength:"250 mg", price:6 },
  { code:"ANT050", brand:"Moxacil Pediatric Drops", generic:"Amoxycillin", strength:"125 mg/1.25ml", price:65 },
  { code:"ANT051", brand:"Moxacil 875 Tablet", generic:"Amoxycillin Trihydrate", strength:"875 mg", price:18 },
  { code:"ANT052", brand:"Moxaclav 375 Tablet", generic:"Amoxycillin + Clavulanic acid", strength:"250+125 mg", price:25 },
  { code:"ANT053", brand:"Moxaclav 625 Tablet", generic:"Amoxycillin + Clavulanic acid", strength:"500+125 mg", price:40 },
  { code:"ANT054", brand:"Moxaclav Dry Syrup", generic:"Amoxycillin + Clavulanic acid", strength:"125+31.25 mg/5ml", price:130 },
  { code:"ANT055", brand:"Moxaclav Forte Suspension", generic:"Amoxycillin + Clavulanic acid", strength:"400+57.50 mg/5ml", price:180 },
  { code:"ANT056", brand:"Moxaclav 1gm Tablet", generic:"Amoxycillin + Clavulanic acid", strength:"875+125 mg", price:65 },
  { code:"ANT057", brand:"Nalid 500 Tablet", generic:"Nalidixic Acid", strength:"500 mg", price:5 },
  { code:"ANT058", brand:"Nalid Dry Syrup", generic:"Nalidixic Acid", strength:"300 mg/5ml", price:70 },
  { code:"ANT059", brand:"Penvik Dry Syrup", generic:"Phenoxymethyl Penicillin", strength:"125 mg/5ml", price:75 },
  { code:"ANT060", brand:"Penvik 250 Tablet", generic:"Phenoxymethyl Penicillin", strength:"250 mg", price:6 },
  { code:"ANT061", brand:"Penvik DS Tablet", generic:"Phenoxymethyl Penicillin", strength:"500 mg", price:10 },
  { code:"ANT062", brand:"Penvik Forte Dry Syrup", generic:"Phenoxymethyl Penicillin", strength:"250 mg/5ml", price:120 },
  { code:"ANT063", brand:"Phylopen 250 Capsule", generic:"Flucloxacillin", strength:"250 mg", price:8 },
  { code:"ANT064", brand:"Phylopen Dry Syrup", generic:"Flucloxacillin", strength:"125 mg/5ml", price:80 },
  { code:"ANT065", brand:"Phylopen Forte Dry Syrup", generic:"Flucloxacillin", strength:"250 mg/5ml", price:130 },
  { code:"ANT066", brand:"Phylopen DS Capsule", generic:"Flucloxacillin", strength:"500 mg", price:15 },
  { code:"ANT067", brand:"Phylopen 500 Injection", generic:"Flucloxacillin", strength:"500 mg/vial", price:90 },
  { code:"ANT068", brand:"Remac 500 Tablet", generic:"Clarithromycin", strength:"500 mg", price:60 },
  { code:"ANT069", brand:"Rutix 200 Tablet", generic:"Ofloxacin", strength:"200 mg", price:12 },
  { code:"ANT070", brand:"Rutix 400 Tablet", generic:"Ofloxacin", strength:"400 mg", price:20 },
  { code:"ANT071", brand:"Saga 200mg Tablet", generic:"Sparfloxacin", strength:"200 mg", price:25 },
  { code:"ANT072", brand:"Specbac 1gm IV Injection", generic:"Meropenem", strength:"1 gm", price:900 },
  { code:"ANT073", brand:"Specbac 500mg IV Injection", generic:"Meropenem", strength:"500 mg", price:500 },
  { code:"ANT074", brand:"Tazid 250mg IM/IV Injection", generic:"Ceftazidime", strength:"250 mg", price:100 },
  { code:"ANT075", brand:"Tazid 500mg IM/IV Injection", generic:"Ceftazidime", strength:"500 mg", price:175 },
  { code:"ANT076", brand:"Tazid 1gm IM/IV Injection", generic:"Ceftazidime", strength:"1 gm", price:300 },
  { code:"ANT077", brand:"Tetrax 500 Capsule", generic:"Tetracycline HCl", strength:"500 mg", price:4 },
  { code:"ANT078", brand:"Trevox 500 Tablet", generic:"Levofloxacin", strength:"500 mg", price:35 },
  { code:"ANT079", brand:"Trevox 750 Tablet", generic:"Levofloxacin", strength:"750 mg", price:55 },
  { code:"ANT080", brand:"Trevox Syrup", generic:"Levofloxacin", strength:"125 mg/5ml", price:140 },
  { code:"ANT081", brand:"Vanprox 100 Capsule", generic:"Cefpodoxime Proxetile", strength:"100 mg", price:30 },
  { code:"ANT082", brand:"Vanprox 200 Capsule", generic:"Cefpodoxime Proxetile", strength:"200 mg", price:55 },
  { code:"ANT083", brand:"Vanprox Pediatric Drops", generic:"Cefpodoxime Proxetile", strength:"20 mg/ml", price:110 },
  { code:"ANT084", brand:"Vanprox Dry Syrup", generic:"Cefpodoxime Proxetile", strength:"40 mg/5ml", price:130 },
  { code:"ANT085", brand:"Vanprox Forte Suspension", generic:"Cefpodoxime Proxetile USP", strength:"80 mg/5ml", price:180 },
  { code:"ANT086", brand:"Zimax 500 Tablet", generic:"Azithromycin", strength:"500 mg", price:55 },
  { code:"ANT087", brand:"Zimax 250 Capsule", generic:"Azithromycin", strength:"250 mg", price:30 },
  { code:"ANT088", brand:"Zimax Suspension", generic:"Azithromycin", strength:"200 mg/5ml", price:160 },

  // ANALGESIC, ANTIPYRETIC, ANTIRHEUMATIC AND ANTISPASMODIC
  { code:"ANA001", brand:"Ace Pediatric Drops", generic:"Paracetamol", strength:"80 mg/ml", price:30 },
  { code:"ANA002", brand:"Ace Suspension", generic:"Paracetamol", strength:"120 mg/5ml", price:50 },
  { code:"ANA003", brand:"Ace Syrup", generic:"Paracetamol", strength:"120 mg/5ml", price:50 },
  { code:"ANA004", brand:"Ace 500 Tablet", generic:"Paracetamol", strength:"500 mg", price:1.2 },
  { code:"ANA005", brand:"ACE 60 Suppository", generic:"Paracetamol", strength:"60 mg", price:20.7 },
  { code:"ANA006", brand:"ACE 125 Suppository", generic:"Paracetamol", strength:"125 mg", price:6 },
  { code:"ANA007", brand:"ACE 250 Suppository", generic:"Paracetamol", strength:"250 mg", price:7 },
  { code:"ANA008", brand:"ACE 500 Suppository", generic:"Paracetamol", strength:"500 mg", price:10 },
  { code:"ANA009", brand:"Ace Plus Tablet", generic:"Paracetamol + Caffeine", strength:"500+65 mg", price:2.5 },
  { code:"ANA010", brand:"Anadol Capsule", generic:"Tramadol HCl", strength:"50 mg", price:8 },
  { code:"ANA011", brand:"Anadol Injection", generic:"Tramadol HCl", strength:"100 mg/2ml", price:25 },
  { code:"ANA012", brand:"Anadol Suppository", generic:"Tramadol HCl", strength:"100 mg", price:30 },
  { code:"ANA013", brand:"Clofenac 25 Tablet", generic:"Diclofenac Sodium", strength:"25 mg", price:2 },
  { code:"ANA014", brand:"Clofenac 50 Tablet", generic:"Diclofenac Sodium", strength:"50 mg", price:3 },
  { code:"ANA015", brand:"Clofenac 100 TR Capsule", generic:"Diclofenac Sodium BP", strength:"100 mg", price:7 },
  { code:"ANA016", brand:"Clofenac DT", generic:"Diclofenac free acid", strength:"46.50 mg", price:5 },
  { code:"ANA017", brand:"Clofenac Gel", generic:"Diclofenac Diethylammonium Salt", strength:"10 mg/gm", price:80 },
  { code:"ANA018", brand:"Clofenac Injection", generic:"Diclofenac Sodium", strength:"75 mg/3ml", price:18 },
  { code:"ANA019", brand:"Clofenac Plus Injection", generic:"Diclofenac Sodium + Lidocaine", strength:"(75+20) mg/2ml", price:22 },
  { code:"ANA020", brand:"Clofenac SR Tablet", generic:"Diclofenac Sodium", strength:"100 mg", price:8 },
  { code:"ANA021", brand:"Clofenac 12.5 Suppository", generic:"Diclofenac Sodium", strength:"12.5 mg", price:15 },
  { code:"ANA022", brand:"Clofenac 25 Suppository", generic:"Diclofenac Sodium", strength:"25 mg", price:18 },
  { code:"ANA023", brand:"Clofenac 50 Suppository", generic:"Diclofenac Sodium", strength:"50 mg", price:22 },
  { code:"ANA024", brand:"Colicon Tablet", generic:"Dicycloverine", strength:"10 mg", price:4 },
  { code:"ANA025", brand:"Colicon Injection", generic:"Dicycloverine", strength:"20 mg/2ml", price:20 },
  { code:"ANA026", brand:"Colicon Syrup", generic:"Dicycloverine", strength:"10 mg/5ml", price:60 },
  { code:"ANA027", brand:"Contilex Tablet", generic:"Glucosamine Sulfate + Chondroitin Sulfate", strength:"250+200 mg", price:25 },
  { code:"ANA028", brand:"Espa Tablet", generic:"Drotaverine HCl", strength:"40 mg", price:6 },
  { code:"ANA029", brand:"Espa Injection", generic:"Drotaverine HCl", strength:"40 mg/2ml", price:25 },
  { code:"ANA030", brand:"Flexi Tablet", generic:"Aceclofenac", strength:"100 mg", price:8 },
  { code:"ANA031", brand:"Kitex Tablet", generic:"Dexketoprofen", strength:"25 mg", price:15 },
  { code:"ANA032", brand:"Kop 200 SR Capsule", generic:"Ketoprofen", strength:"200 mg", price:20 },
  { code:"ANA033", brand:"Kop 50 Tablet", generic:"Ketoprofen", strength:"50 mg", price:8 },
  { code:"ANA034", brand:"Kop 100 SR Capsule", generic:"Ketoprofen", strength:"100 mg", price:15 },
  { code:"ANA035", brand:"Kop Gel", generic:"Ketoprofen", strength:"25 mg/gm", price:70 },
  { code:"ANA036", brand:"Kop IM Injection", generic:"Ketoprofen", strength:"100 mg/2ml", price:30 },
  { code:"ANA037", brand:"Melcam 7.5 Tablet", generic:"Meloxicam", strength:"7.5 mg", price:6 },
  { code:"ANA038", brand:"Melcam 15 Tablet", generic:"Meloxicam", strength:"15 mg", price:10 },
  { code:"ANA039", brand:"Miclofenac 50 Tablet", generic:"Diclofenac Sodium + Misoprostol", strength:"50+200 mcg", price:12 },
  { code:"ANA040", brand:"Miclofenac 75 Tablet", generic:"Diclofenac Sodium + Misoprostol", strength:"75+200 mcg", price:18 },
  { code:"ANA041", brand:"Norvis Tablet", generic:"Tiemonium Methylsulphate", strength:"50 mg", price:8 },
  { code:"ANA042", brand:"Norvis Injection", generic:"Tiemonium Methylsulphate", strength:"5 mg/2ml", price:20 },
  { code:"ANA043", brand:"Panodin SR Tablet", generic:"Etodolac USP", strength:"600 mg", price:25 },
  { code:"ANA044", brand:"Penrif 15 Cream", generic:"Methylsalicylate + Menthol", strength:"15%+10%", price:60 },
  { code:"ANA045", brand:"Penrif 30 Cream", generic:"Methylsalicylate + Menthol", strength:"30%+8%", price:80 },
  { code:"ANA046", brand:"Sonap 10% Gel", generic:"Naproxen", strength:"10%", price:70 },
  { code:"ANA047", brand:"Sonap 250 Tablet", generic:"Naproxen", strength:"250 mg", price:5 },
  { code:"ANA048", brand:"Sonap 500 Tablet", generic:"Naproxen", strength:"500 mg", price:8 },
  { code:"ANA049", brand:"Sonap 500 Suppository", generic:"Naproxen", strength:"500 mg", price:25 },
  { code:"ANA050", brand:"Tilex 500 Tablet", generic:"Glucosamine HCl", strength:"500 mg", price:15 },
  { code:"ANA051", brand:"Torax 10 Tablet", generic:"Ketorolac Tromethamine", strength:"10 mg", price:10 },
  { code:"ANA052", brand:"Torax 10 Injection", generic:"Ketorolac Tromethamine", strength:"10 mg/ml", price:25 },
  { code:"ANA053", brand:"Torax 30 Injection", generic:"Ketorolac Tromethamine", strength:"30 mg/ml", price:40 },
  { code:"ANA054", brand:"Torax 60 Injection", generic:"Ketorolac Tromethamine", strength:"60 mg/ml", price:65 },
  { code:"ANA055", brand:"Tory 60 Tablet", generic:"Etoricoxib", strength:"60 mg", price:18 },
  { code:"ANA056", brand:"Tory 90 Tablet", generic:"Etoricoxib", strength:"90 mg", price:25 },
  { code:"ANA057", brand:"Tory 120 Tablet", generic:"Etoricoxib", strength:"120 mg", price:35 },
  { code:"ANA058", brand:"Xflam 200 Tablet", generic:"Dex-Ibuprofen INN", strength:"200 mg", price:5 },
  { code:"ANA059", brand:"Xflam 300 Tablet", generic:"Dex-Ibuprofen INN", strength:"300 mg", price:8 },
  { code:"ANA060", brand:"Xflam 400 Tablet", generic:"Dex-Ibuprofen INN", strength:"400 mg", price:10 },
  { code:"ANA061", brand:"Xripa Tablet", generic:"Nefopam HCl INN", strength:"30 mg", price:15 },
  { code:"ANA062", brand:"Xripa Injection", generic:"Nefopam HCl INN", strength:"20 mg/ml", price:40 },
  { code:"ANA063", brand:"Xtra 10 Tablet", generic:"Valdecoxib", strength:"10 mg", price:15 },
  { code:"ANA064", brand:"Xtra 20 Tablet", generic:"Valdecoxib", strength:"20 mg", price:25 },
  { code:"ANA065", brand:"Timotor Tablet", generic:"Trimebutine Maleate INN", strength:"100 mg", price:10 },

  // GASTROPROKINETIC AND ANTIEMETIC
  { code:"GAS001", brand:"Motigut Suspension", generic:"Domperidone", strength:"5 mg/5ml", price:60 },
  { code:"GAS002", brand:"Motigut Tablet", generic:"Domperidone", strength:"10 mg", price:4 },
  { code:"GAS003", brand:"Motigut Paediatric Drops", generic:"Domperidone", strength:"5 mg/ml", price:55 },
  { code:"GAS004", brand:"Motifast Tablet", generic:"Domperidone", strength:"5 mg", price:3 },
  { code:"GAS005", brand:"Naurif 1mg Tablet", generic:"Granisetron", strength:"1 mg", price:50 },
  { code:"GAS006", brand:"Naurif 1mg Injection", generic:"Granisetron", strength:"1 mg/ml", price:180 },
  { code:"GAS007", brand:"Vertina Chewable Tablet", generic:"Meclizine", strength:"50 mg", price:8 },

  // ANTIFLATULENT
  { code:"AFL001", brand:"Flacol Paediatric Drops", generic:"Simethicone", strength:"67 mg/ml", price:75 },

  // ANTIALLERGIC AND ANTIHISTAMINE
  { code:"ALG001", brand:"Alatrol Syrup", generic:"Cetirizine Hydrochloride", strength:"5 mg/5ml", price:35 },
  { code:"ALG002", brand:"Alatrol Tablet", generic:"Cetirizine Hydrochloride", strength:"10 mg", price:3 },
  { code:"ALG003", brand:"Alatrol Paediatric Drops", generic:"Cetirizine Hydrochloride", strength:"2.5 mg/ml", price:28 },
  { code:"ALG004", brand:"Alarid Tablet", generic:"Ketotifen Fumerate", strength:"1 mg", price:3 },
  { code:"ALG005", brand:"Alarid Syrup", generic:"Ketotifen Fumerate", strength:"1 mg/5ml", price:75 },
  { code:"ALG006", brand:"Adryl Syrup", generic:"Diphenhydramine HCl", strength:"10 mg/5ml", price:45 },
  { code:"ALG007", brand:"Antista Syrup", generic:"Chlorpheniramine Maleate", strength:"2 mg/5ml", price:40 },
  { code:"ALG008", brand:"Fexo 60 Tablet", generic:"Fexofenadine HCl", strength:"60 mg", price:12 },
  { code:"ALG009", brand:"Fexo 120 Tablet", generic:"Fexofenadine HCl", strength:"120 mg", price:18 },
  { code:"ALG010", brand:"Fexo 180 Tablet", generic:"Fexofenadine HCl", strength:"180 mg", price:25 },
  { code:"ALG011", brand:"Loratin Tablet", generic:"Loratadine", strength:"10 mg", price:4 },
  { code:"ALG012", brand:"Loratin Suspension", generic:"Loratadine", strength:"5 mg/5ml", price:60 },
  { code:"ALG013", brand:"Loratin FT", generic:"Loratadine", strength:"10 mg", price:5 },
  { code:"ALG014", brand:"Sedno Tablet", generic:"Desloratadine", strength:"5 mg", price:12 },
  { code:"ALG015", brand:"Sedno Syrup", generic:"Desloratadine", strength:"2.50 mg/5ml", price:80 },

  // CARDIOVASCULAR
  { code:"CAR001", brand:"Angilock 25 Tablet", generic:"Losartan Potassium", strength:"25 mg", price:6 },
  { code:"CAR002", brand:"Angilock 50 Tablet", generic:"Losartan Potassium", strength:"50 mg", price:10 },
  { code:"CAR003", brand:"Angilock 100 Tablet", generic:"Losartan Potassium", strength:"100 mg", price:18 },
  { code:"CAR004", brand:"Angilock 50 Plus Tablet", generic:"Losartan Potassium + Hydrochlorothiazide", strength:"50+12.5 mg", price:14 },
  { code:"CAR005", brand:"Angilock 100 Plus Tablet", generic:"Losartan Potassium + Hydrochlorothiazide", strength:"100+25 mg", price:22 },
  { code:"CAR006", brand:"Angilock Plus 100/12.5 Tablet", generic:"Losartan Potassium + Hydrochlorothiazide", strength:"100+12.5 mg", price:20 },
  { code:"CAR007", brand:"Anzitor 10 Tablet", generic:"Atorvastatin", strength:"10 mg", price:8 },
  { code:"CAR008", brand:"Anzitor 20 Tablet", generic:"Atorvastatin", strength:"20 mg", price:14 },
  { code:"CAR009", brand:"Anclog Tablet", generic:"Clopidogrel", strength:"75 mg", price:15 },
  { code:"CAR010", brand:"Anclog Plus Tablet", generic:"Clopidogrel + Aspirin", strength:"75+75 mg", price:18 },
  { code:"CAR011", brand:"Anril 0.5 Tablet", generic:"Nitroglycerin", strength:"0.5 mg", price:5 },
  { code:"CAR012", brand:"Anril Spray", generic:"Nitroglycerin USP", strength:"400 mcg/spray", price:350 },
  { code:"CAR013", brand:"Anril SR Tablet", generic:"Nitroglycerin", strength:"2.6 mg", price:8 },
  { code:"CAR014", brand:"ARB-8 Tablet", generic:"Candesartan Cilexetil", strength:"8 mg", price:15 },
  { code:"CAR015", brand:"Camlodin 5 Tablet", generic:"Amlodipine", strength:"5 mg", price:4 },
  { code:"CAR016", brand:"Camlodin 10 Tablet", generic:"Amlodipine", strength:"10 mg", price:7 },
  { code:"CAR017", brand:"Camlodin Plus 25 Tablet", generic:"Amlodipine + Atenolol", strength:"5+25 mg", price:8 },
  { code:"CAR018", brand:"Camlodin Plus 50 Tablet", generic:"Amlodipine + Atenolol", strength:"5+50 mg", price:10 },
  { code:"CAR019", brand:"Camlopril 2.5/10 Capsule", generic:"Amlodipine + Benazepril", strength:"2.5+10 mg", price:15 },
  { code:"CAR020", brand:"Camlopril 5/10 Capsule", generic:"Amlodipine + Benazepril", strength:"5+10 mg", price:20 },
  { code:"CAR021", brand:"Camlopril 5/20 Capsule", generic:"Amlodipine + Benazepril", strength:"5+20 mg", price:25 },
  { code:"CAR022", brand:"Camlopril 10/20 Capsule", generic:"Amlodipine + Benazepril", strength:"10+20 mg", price:30 },
  { code:"CAR023", brand:"Cardipro 50 Tablet", generic:"Atenolol", strength:"50 mg", price:3 },
  { code:"CAR024", brand:"Cardipro 100 Tablet", generic:"Atenolol", strength:"100 mg", price:5 },
  { code:"CAR025", brand:"Cardipro 50 Plus Tablet", generic:"Atenolol + Chlorthalidone", strength:"50+25 mg", price:6 },
  { code:"CAR026", brand:"Cardipro 100 Plus Tablet", generic:"Atenolol + Chlorthalidone", strength:"100+25 mg", price:9 },
  { code:"CAR027", brand:"Carva 75 Tablet", generic:"Aspirin", strength:"75 mg", price:2 },
  { code:"CAR028", brand:"Cerevas Tablet", generic:"Vinpocetine INN", strength:"5 mg", price:10 },
  { code:"CAR029", brand:"Cinaron Tablet", generic:"Cinnarizine", strength:"15 mg", price:3 },
  { code:"CAR030", brand:"Cholinor Tablet", generic:"Ezetimibe", strength:"10 mg", price:30 },
  { code:"CAR031", brand:"Delipid Capsule", generic:"Gemfibrozil", strength:"300 mg", price:10 },
  { code:"CAR032", brand:"Diltizem SR 90 Tablet", generic:"Diltiazem HCl", strength:"90 mg", price:12 },
  { code:"CAR033", brand:"Durol 6.25 Tablet", generic:"Carvedilol", strength:"6.25 mg", price:8 },
  { code:"CAR034", brand:"Durol 12.5 Tablet", generic:"Carvedilol", strength:"12.5 mg", price:14 },
  { code:"CAR035", brand:"Durol 25 Tablet", generic:"Carvedilol", strength:"25 mg", price:20 },
  { code:"CAR036", brand:"Esmo Tablet", generic:"Isosorbide Mononitrate", strength:"20 mg", price:5 },
  { code:"CAR037", brand:"Esmo LA Capsule", generic:"Isosorbide Mononitrate", strength:"50 mg", price:12 },
  { code:"CAR038", brand:"Freflo Tablet", generic:"Frusemide + Spironolactone", strength:"20+50 mg", price:8 },
  { code:"CAR039", brand:"Fusid Injection", generic:"Frusemide", strength:"20 mg/amp", price:15 },
  { code:"CAR040", brand:"Fusid Tablet", generic:"Frusemide", strength:"40 mg", price:2 },
  { code:"CAR041", brand:"Fusid 40 Plus Tablet", generic:"Frusemide + Spironolactone", strength:"40+50 mg", price:10 },
  { code:"CAR042", brand:"Nidipine SR Tablet", generic:"Nifedipine", strength:"20 mg", price:6 },
  { code:"CAR043", brand:"Nimocal Tablet", generic:"Nimodipine", strength:"30 mg", price:20 },
  { code:"CAR044", brand:"Oxyfyl CR Tablet", generic:"Pentoxifylline", strength:"400 mg", price:15 },
  { code:"CAR045", brand:"Levocar Solution", generic:"Levocarnitine", strength:"500 mg/5ml", price:80 },
  { code:"CAR046", brand:"Levocar Tablet", generic:"Levocarnitine", strength:"330 mg", price:25 },
  { code:"CAR047", brand:"Lipired 200 Capsule", generic:"Fenofibrate", strength:"200 mg", price:18 },
  { code:"CAR048", brand:"Repres 1.5 SR Tablet", generic:"Indapamide", strength:"1.5 mg SR", price:12 },
  { code:"CAR049", brand:"Repres Plus 2 Tablet", generic:"Indapamide + Perindopril", strength:"0.625+2 mg", price:15 },
  { code:"CAR050", brand:"Repres Plus 4 Tablet", generic:"Indapamide + Perindopril", strength:"1.25+4 mg", price:20 },
  { code:"CAR051", brand:"Ripril 1.25 Capsule", generic:"Ramipril", strength:"1.25 mg", price:5 },
  { code:"CAR052", brand:"Ripril 2.5 Capsule", generic:"Ramipril", strength:"2.5 mg", price:8 },
  { code:"CAR053", brand:"Ripril 5 Capsule", generic:"Ramipril", strength:"5 mg", price:12 },
  { code:"CAR054", brand:"Ripril 10 Capsule", generic:"Ramipril", strength:"10 mg", price:18 },
  { code:"CAR055", brand:"Ripril 1.25 Tablet", generic:"Ramipril", strength:"1.25 mg", price:5 },
  { code:"CAR056", brand:"Ripril 2.5 Tablet", generic:"Ramipril", strength:"2.5 mg", price:8 },
  { code:"CAR057", brand:"Ripril 5 Tablet", generic:"Ramipril", strength:"5 mg", price:12 },
  { code:"CAR058", brand:"Ripril Plus 2.5/12.5 Tablet", generic:"Ramipril + Hydrochlorothiazide", strength:"2.5+12.5 mg", price:12 },
  { code:"CAR059", brand:"Ripril Plus 5/25 Tablet", generic:"Ramipril + Hydrochlorothiazide", strength:"5+25 mg", price:18 },
  { code:"CAR060", brand:"Rosuva 10 Tablet", generic:"Rosuvastatin", strength:"10 mg", price:20 },
  { code:"CAR061", brand:"Simacor 10 Tablet", generic:"Simvastatin", strength:"10 mg", price:8 },
  { code:"CAR062", brand:"Vasopril 5 Tablet", generic:"Enalapril Maleate", strength:"5 mg", price:4 },
  { code:"CAR063", brand:"Vasopril 10 Tablet", generic:"Enalapril Maleate", strength:"10 mg", price:7 },

  // ANTIHELMINTIC
  { code:"HLM001", brand:"Almex Suspension", generic:"Albendazole", strength:"200 mg/5ml", price:23 },
  { code:"HLM002", brand:"Almex Tablet", generic:"Albendazole", strength:"400 mg", price:5 },
  { code:"HLM003", brand:"Ermox 100 Tablet", generic:"Mebendazole", strength:"100 mg", price:4 },
  { code:"HLM004", brand:"Ermox Suspension", generic:"Mebendazole", strength:"100 mg/5ml", price:55 },

  // ANTIAMOEBIC, ANTIPROTOZOAL, ANTIFUNGAL
  { code:"AMB001", brand:"Amodis 400 Tablet", generic:"Metronidazole", strength:"400 mg", price:4 },
  { code:"AMB002", brand:"Amodis Suspension", generic:"Metronidazole", strength:"200 mg/5ml", price:55 },
  { code:"AMB003", brand:"Candex Suspension", generic:"Nystatin", strength:"0.1 million unit", price:80 },
  { code:"AMB004", brand:"Flugal 150 Capsule", generic:"Fluconazole", strength:"150 mg", price:30 },
  { code:"AMB005", brand:"Flugal 50 Capsule", generic:"Fluconazole", strength:"50 mg", price:12 },
  { code:"AMB006", brand:"Flugal Suspension", generic:"Fluconazole", strength:"50 mg/5ml", price:90 },
  { code:"AMB007", brand:"Itra Capsule", generic:"Itraconazole", strength:"100 mg", price:45 },
  { code:"AMB008", brand:"Ketoral 200 Tablet", generic:"Ketoconazole", strength:"200 mg", price:10 },
  { code:"AMB009", brand:"Robic Tablet", generic:"Ornidazole", strength:"500 mg", price:18 },
  { code:"AMB010", brand:"Secnid 500 Suspension", generic:"Secnidazole", strength:"500 mg", price:70 },
  { code:"AMB011", brand:"Secnid DS Tablet", generic:"Secnidazole", strength:"1 gm", price:30 },

  // VITAMINS AND MINERALS
  { code:"VIT001", brand:"B-50 Forte Capsule", generic:"Vitamin B Complex", strength:"", price:8 },
  { code:"VIT002", brand:"B-50 Forte Injection", generic:"Vitamin B Complex", strength:"", price:30 },
  { code:"VIT003", brand:"B-50 Forte Syrup", generic:"Vitamin B Complex", strength:"", price:70 },
  { code:"VIT004", brand:"B-50 Forte Tablet", generic:"Vitamin B Complex", strength:"", price:5 },
  { code:"VIT005", brand:"Beovit Tablet", generic:"Thiamine HCl", strength:"100 mg", price:3 },
  { code:"VIT006", brand:"Bicozin Syrup", generic:"Vit B1+B12+B6+Nicotinamide+Zinc", strength:"5+2+2+20+10 mg/5ml", price:80 },
  { code:"VIT007", brand:"Bicozin Tablet", generic:"Vit B1+B2+B3+B6+Zinc", strength:"5+2+20+2+10 mg", price:5 },
  { code:"VIT008", brand:"Calbo Tablet", generic:"Calcium Carbonate", strength:"500 mg", price:5 },
  { code:"VIT009", brand:"Calbo Junior Tablet", generic:"Calcium Carbonate", strength:"250 mg", price:3 },
  { code:"VIT010", brand:"Calbo-C Effervescent Tablet", generic:"Calcium Lactate+Calcium Carbonate+Ascorbic Acid", strength:"1000+327+500 mg", price:25 },
  { code:"VIT011", brand:"Calbo-D Tablet", generic:"Calcium Carbonate + Cholecalciferol", strength:"500 mg+200 IU", price:8 },
  { code:"VIT012", brand:"Calbo Forte Effervescent Tablet", generic:"Calcium Carbonate+Vitamin C+Vitamin D", strength:"1000+500 mg+400 IU", price:35 },
  { code:"VIT013", brand:"Calboplex Tablet", generic:"Calcium+Vitamin D+Mg+Mn+Cu+Zn", strength:"600 mg+200 IU", price:12 },
  { code:"VIT014", brand:"Ceevit Tablet", generic:"Ascorbic acid+Sodium Ascorbate", strength:"250 mg", price:3 },
  { code:"VIT015", brand:"Ceevit Forte Effervescent Tablet", generic:"Ascorbic acid", strength:"1000 mg", price:20 },
  { code:"VIT016", brand:"Evit Tablet", generic:"Vitamin E", strength:"200 mg", price:5 },
  { code:"VIT017", brand:"Evit 400 Licap", generic:"Vitamin E", strength:"400 mg", price:12 },
  { code:"VIT018", brand:"Eyevi Capsule", generic:"Vitamin C+E+Zinc+Copper+Lutein", strength:"60+30 IU+15+2+6 mg", price:30 },
  { code:"VIT019", brand:"Filwel Silver", generic:"Multivitamin multimineral (45+)", strength:"", price:25 },
  { code:"VIT020", brand:"Filwel Gold", generic:"Multivitamin multimineral (<45)", strength:"", price:25 },
  { code:"VIT021", brand:"Filwel Kids Syrup", generic:"Multivitamin multimineral (children)", strength:"", price:100 },
  { code:"VIT022", brand:"Methicol Tablet", generic:"Mecobalamin INN", strength:"500 mcg", price:10 },
  { code:"VIT023", brand:"Methicol Injection", generic:"Mecobalamin INN", strength:"500 mcg", price:35 },
  { code:"VIT024", brand:"Multivit Plus Tablet", generic:"Multivitamin-multimineral", strength:"", price:8 },
  { code:"VIT025", brand:"Neuro-B Tablet", generic:"Vitamin B1+B6+B12", strength:"100+200 mg+200 mcg", price:8 },
  { code:"VIT026", brand:"Neuro-B Injection", generic:"Vitamin B1+B6+B12", strength:"100+100 mg+1000 mcg", price:40 },
  { code:"VIT027", brand:"Panvit Drops", generic:"Multivitamin drops", strength:"", price:55 },
  { code:"VIT028", brand:"Rex Tablet", generic:"Beta Carotene+Vit C+Vit E", strength:"6+200+50 mg", price:10 },
  { code:"VIT029", brand:"Zesup Syrup", generic:"Zinc Sulphate", strength:"10 mg Zn/5ml", price:60 },
  { code:"VIT030", brand:"Zesup Forte Syrup", generic:"Zinc Sulphate", strength:"20 mg Zn/5ml", price:80 },
  { code:"VIT031", brand:"Z-DT 10", generic:"Zinc Sulphate", strength:"10 mg", price:2 },
  { code:"VIT032", brand:"Z-DT 20", generic:"Zinc Sulphate", strength:"20 mg", price:3 },

  // ANTIULCERANT
  { code:"ULC001", brand:"Isovent 200 Tablet", generic:"Misoprostol", strength:"200 mcg", price:15 },
  { code:"ULC002", brand:"Isovent 100 Tablet", generic:"Misoprostol INN", strength:"100 mcg", price:10 },
  { code:"ULC003", brand:"Entacyd Plus Suspension", generic:"Antacid + Simethicone", strength:"", price:70 },
  { code:"ULC004", brand:"Entacyd Plus Tablet", generic:"Antacid + Simethicone", strength:"", price:22.5 },
  { code:"ULC005", brand:"Entacyd Suspension", generic:"Antacid", strength:"", price:55 },
  { code:"ULC006", brand:"Entacyd Tablet", generic:"Antacid", strength:"", price:3 },
  { code:"ULC007", brand:"Famotack 20 Tablet", generic:"Famotidine", strength:"20 mg", price:5 },
  { code:"ULC008", brand:"Famotack 40 Tablet", generic:"Famotidine", strength:"40 mg", price:8 },
  { code:"ULC009", brand:"Lanso 15 Capsule", generic:"Lansoprazole", strength:"15 mg", price:10 },
  { code:"ULC010", brand:"Lanso 30 Capsule", generic:"Lansoprazole", strength:"30 mg", price:18 },
  { code:"ULC011", brand:"Neotack 150 Tablet", generic:"Ranitidine HCl", strength:"150 mg", price:3 },
  { code:"ULC012", brand:"Neotack 300 Tablet", generic:"Ranitidine HCl", strength:"300 mg", price:5 },
  { code:"ULC013", brand:"Neotack Injection", generic:"Ranitidine HCl", strength:"50 mg/2ml", price:15 },
  { code:"ULC014", brand:"Neotack Syrup", generic:"Ranitidine HCl", strength:"75 mg/5ml", price:60 },
  { code:"ULC015", brand:"Nexum 20 Capsule", generic:"Esomeprazole", strength:"20 mg", price:70.2 },
  { code:"ULC016", brand:"Nexum 40 Capsule", generic:"Esomeprazole", strength:"40 mg", price:110 },
  { code:"ULC017", brand:"Nexum 20 Tablet", generic:"Esomeprazole", strength:"20 mg", price:65 },
  { code:"ULC018", brand:"Nexum 40 Tablet", generic:"Esomeprazole", strength:"40 mg", price:100 },
  { code:"ULC019", brand:"Pylotrip", generic:"Lansoprazole+Clarithromycin+Amoxycillin", strength:"30+500 mg+1 gm", price:280 },
  { code:"ULC020", brand:"Seclo 20 Capsule", generic:"Omeprazole", strength:"20 mg", price:4 },
  { code:"ULC021", brand:"Seclo 40 Capsule", generic:"Omeprazole", strength:"40 mg", price:7 },
  { code:"ULC022", brand:"Seclo DR 20 Tablet", generic:"Omeprazole BP", strength:"20 mg", price:5 },
  { code:"ULC023", brand:"Trupan 20 Tablet", generic:"Pantoprazole", strength:"20 mg", price:8 },
  { code:"ULC024", brand:"Trupan 40 Tablet", generic:"Pantoprazole", strength:"40 mg", price:14 },
  { code:"ULC025", brand:"Xcid Tablet", generic:"Calcium Carbonate", strength:"1000 mg", price:5 },
  { code:"ULC026", brand:"Apsol Oral Paste", generic:"Amlexanox", strength:"5%", price:120 },

  // NASAL DROPS
  { code:"NAS001", brand:"Antazol Nasal Drop 0.05%", generic:"Xylometazoline HCl", strength:"0.05%", price:40 },
  { code:"NAS002", brand:"Antazol Nasal Drop 0.1%", generic:"Xylometazoline HCl", strength:"0.10%", price:45 },
  { code:"NAS003", brand:"Antazol Plus Nasal Spray", generic:"Xylometazoline + Sodium Cromoglycate", strength:"0.0325+2.6 mg/spray", price:90 },
  { code:"NAS004", brand:"Nacromin 2% Nasal Drops", generic:"Sodium Cromoglycate", strength:"20 mg/ml", price:80 },
  { code:"NAS005", brand:"Nocon 0.05% Nasal Drops", generic:"Oxymetazoline USP", strength:"0.05%", price:45 },
  { code:"NAS006", brand:"Nocon 0.025% Nasal Drops", generic:"Oxymetazoline USP", strength:"0.025%", price:40 },
  { code:"NAS007", brand:"Becospray", generic:"Beclomethasone dipropionate", strength:"50 mcg/spray", price:200 },
  { code:"NAS008", brand:"Flonaspray", generic:"Fluticasone propionate", strength:"50 mcg/spray", price:220 },
  { code:"NAS009", brand:"Rynaspray", generic:"Ipratropium Bromide", strength:"21 mcg/spray", price:180 },
  { code:"NAS010", brand:"Snizex Nasal Spray", generic:"Azelastine HCl BP", strength:"137 mcg/spray", price:250 },
  { code:"NAS011", brand:"Trispray", generic:"Triamcinolone Acetonide", strength:"55 mcg/spray", price:200 },

  // TOPICAL PREPARATIONS
  { code:"TOP001", brand:"Kensten Cream", generic:"Clotrimazole", strength:"1%", price:35 },
  { code:"TOP002", brand:"Kensten-VT (Vaginal Tablet)", generic:"Clotrimazole", strength:"100 mg", price:20 },
  { code:"TOP003", brand:"Betameson-N Cream", generic:"Betamethasone+Neomycin", strength:"1+5 mg/gm", price:50 },
  { code:"TOP004", brand:"De-Rash Ointment", generic:"Zinc oxide", strength:"40%", price:60 },
  { code:"TOP005", brand:"Dermasol Cream", generic:"Clobetasol Propionate", strength:"0.05%", price:45 },
  { code:"TOP006", brand:"Dermasol-N Cream", generic:"Clobetasol+Neomycin+Nystatin", strength:"0.5+5 mg+1lac unit/gm", price:55 },
  { code:"TOP007", brand:"Dermasol Ointment", generic:"Clobetasol Propionate", strength:"0.05%", price:45 },
  { code:"TOP008", brand:"Dermasol-N Ointment", generic:"Clobetasol+Neomycin+Nystatin", strength:"0.5+5 mg+1lac unit/gm", price:55 },
  { code:"TOP009", brand:"Diprobet Cream", generic:"Betamethasone Dipropionate BP", strength:"0.5 mg/gm", price:50 },
  { code:"TOP010", brand:"Diprobet Ointment", generic:"Betamethasone Dipropionate BP", strength:"0.5 mg/gm", price:50 },
  { code:"TOP011", brand:"Equra Cream", generic:"Urea", strength:"10%", price:80 },
  { code:"TOP012", brand:"Eromycin 3% Lotion", generic:"Erythromycin", strength:"3%", price:90 },
  { code:"TOP013", brand:"Ezex 0.05% Cream", generic:"Clobetasone Butyrate", strength:"0.05%", price:40 },
  { code:"TOP014", brand:"Ezex 0.05% Ointment", generic:"Clobetasone Butyrate", strength:"0.05%", price:40 },
  { code:"TOP015", brand:"Fona Cream", generic:"Adapalene", strength:"0.10%", price:120 },
  { code:"TOP016", brand:"Fungidal HC Cream", generic:"Miconazole nitrate+Hydrocortisone", strength:"20+10 mg/g", price:65 },
  { code:"TOP017", brand:"Fungidal Cream", generic:"Miconazole nitrate", strength:"20 mg/gm", price:50 },
  { code:"TOP018", brand:"Pevitin Cream", generic:"Econazole Nitrate+Triamcinolone Acetonide", strength:"1%+0.1%", price:60 },
  { code:"TOP019", brand:"Genacyn Topical Ointment", generic:"Gentamicin", strength:"1 mg/gm", price:35 },
  { code:"TOP020", brand:"Gelora Gel", generic:"Miconazole", strength:"2% W/W", price:55 },
  { code:"TOP021", brand:"Nebanol Ointment", generic:"Neomycin Sulphate+Bacitracin", strength:"5+9.16 mg/g", price:45 },
  { code:"TOP022", brand:"Nebanol Powder", generic:"Neomycin sulphate+Bacitracin", strength:"5+4.56 mg/g", price:50 },
  { code:"TOP023", brand:"Nebanol Plus Ointment", generic:"Neomycin+Bacitracin+Polymixin", strength:"3.5 mg+400 IU+5000 IU", price:55 },
  { code:"TOP024", brand:"Nilac Gel", generic:"Tretinoin", strength:"0.03%", price:100 },
  { code:"TOP025", brand:"Oni Cream", generic:"Betamethasone DP+Clotrimazole", strength:"0.05%+1%", price:55 },
  { code:"TOP026", brand:"Remus Ointment", generic:"Tacrolimus", strength:"0.01%", price:200 },
  { code:"TOP027", brand:"Scabex Cream", generic:"Permethrin", strength:"5%", price:80 },
  { code:"TOP028", brand:"Ticas 0.005% Ointment", generic:"Fluticasone Propionate", strength:"0.005%", price:60 },
  { code:"TOP029", brand:"Ticas 0.05% Cream", generic:"Fluticasone Propionate", strength:"0.05%", price:65 },
  { code:"TOP030", brand:"Topicort Cream", generic:"Hydrocortisone Acetate", strength:"1%", price:40 },
  { code:"TOP031", brand:"Xfin Cream", generic:"Terbinafine", strength:"1%", price:90 },
  { code:"TOP032", brand:"Bactrocin 2% Ointment", generic:"Mupirocin", strength:"2%", price:120 },
];

// Seed default inventory if none exists yet
(function seedInventory() {
  if (localStorage.getItem("inventory")) return;
  const inventory = {};
  medications.forEach(m => {
    inventory[m.code] = Math.floor(Math.random() * 16) + 5; // random 5–20
  });
  localStorage.setItem("inventory", JSON.stringify(inventory));
})();